name: test

on:
  pull_request:
    types:
      - closed
    paths:
      - "README.md"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check PR merge
        if: github.event.pull_request.merged == true
        run: echo 通常のマージだよ

      - name: check PR auto merge
        if: github.event.pull_request.auto_merge != null
        run: echo auto merge だよ

      - name: check deploy
        if: |
          github.event.pull_request.merged == true ||
          github.event.pull_request.auto_merge != null
        run: echo デプロイするよ

      - name: echo github
        run: echo '${{ toJSON(github) }}'
