name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo github.event_name
        run: echo '${{ github.event_name }}'

      - name: echo github.event.type
        run: echo '${{ github.event.type }}'

      - name: echo github.event.pull_request.auto_merge
        run: echo '${{ github.event.pull_request.auto_merge }}'

      - name: echo github.event
        run: echo '${{ github.event }}'
