name: test

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - ".github/workflows/test.yml"
  pull_request:
    types:
      - closed
    paths:
      - "README.md"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check push
        if: github.event_name == 'push'
        run: echo プッシュだよ

      - name: check PR auto merge
        if: github.event_name == 'pull_request' && github.event.pull_request.auto_merge != null
        run: echo auto merge だよ

      - name: echo github
        run: echo '${{ toJSON(github) }}'
