name: test

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "./github/workflows/test.yml"
  pull_request:
    paths:
      - "README.md"
      - "./github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo github.event_name
        run: echo '${{ github.event_name }}'

      - name: echo github.event.type
        run: echo '${{ github.event.type }}'

      - name: echo github.event.pull_request.auto_merge
        run: echo '${{ github.event.pull_request.auto_merge }}'

      - name: echo github.event
        run: echo '${{ toJSON(github.event) }}'
